### ISSUE TITLE
[yq] 'select() | .foo' makes empty values reappear

### ISSUE THREAD

**Issue by preaction** [preaction/ETL-Yertl#132]
Using `select()` will either return a document or not based on the expression inside. But when we pipe the output of select into a document selector, the empty return from the `select()` turns into an undef element in the output stream.

```yaml
# test.yml
---
foo: 1
bar: 2
---
foo: 1
bar: 3
---
foo: 2
bar: 4
---
foo: 1
bar: 5
```

Select by itself gives only the 3 expected documents.

```
$ yq 'select( .foo == 1 )' test.yml
---
bar: 2
foo: 1
---
bar: 3
foo: 1
---
bar: 5
foo: 1
```

Select with a pipe gives 4 documents, one of which is undefined (`~`).

```
$ yq 'select( .foo == 1 ) | .bar' test.yml
--- 2
--- 3
--- ~
--- 5
```
