### ISSUE TITLE
[yfrom][yto] CSV format should allow multiple header lines

### ISSUE THREAD

**Issue by preaction** [preaction/ETL-Yertl#42]
Deeper data structures can be modeled with additional header lines, like

``` csv
FOO,FOO,BAR,BAR
A,B,A,B
1,2,3,4
5,6,7,8
```

Could yield:

``` yaml
FOO:
    - A: 1
      B: 2
    - A: 5
      B: 6
BAR:
    - A: 3
      B: 4
    - A: 7
      B: 8
```

Hash of hashes is the only thing I want to do with this for now.
