### ISSUE TITLE
[ysql] String interpolation for deep data structures

### ISSUE THREAD

**Issue by preaction** [preaction/ETL-Yertl#70]
We should standardize on a single interpolation syntax. Right now, my best idea is `$.[\w.]+`. `$.` introduces the interpolation, and then everything else is like yq's filter syntax. So:

```yaml
---
name: FOO
fields:
    address: 123 Bar St.
    state: Denial
```

```
INSERT INTO foo ( name, address, state ) 
VALUES ( $.name, $.fields.address, $.fields.state )
```
